### ISSUE TITLE
PSR compliance

### ISSUE THREAD

**Issue by Potherca** [poef/simpleBus#1]
Seriously, your use of tabs is killing me. Looking at the code on github is giving me a headache. SPACES! SPACES! SPACES!

And all of that other crap, of course. But mostly SPAAAACES!

:-P

**Comment by poef** [comment]
Seriously? Spaces? Doesn't everybody use sane text editors these days that can handle whatever you want to use? But if you want to update the code to use spaaaaces, by all means send me a pull request and I'll apply it.
